import = [
"~/.config/alacritty/themes/tokyo-night.toml"
]

[window]
padding = { x = 5, y = 5}
decorations = "None"
dynamic_title = true
opacity = 0.7
blur = true
startup_mode = "Maximized"

[font]
normal = { family = "JetBrainsMonoNL Nerd Font Mono", style = "Regular" }
size = 12
